README: Add explanations on scripts

diff --git a/scripts/install_lein b/scripts/install_lein
--- a/scripts/install_lein
+++ b/scripts/install_lein
@@ -1,8 +1,29 @@
 #!/bin/bash
 
-install_lein() {
-    echo "Installing lein..."
+function yes_or_no {
+    while true; do
+        read -p "$* [y/n]: " yn
+        case $yn in
+            [Yy]*) return 0 ;;  
+            [Nn]*) return 1 ;;
+        esac
+    done
+}
+
+function install_lein {
     lein="${HOME}/bin/lein"
+
+    if [ -e ${lein} ]; then
+        lein -v
+        yes_or_no "lein is already installed, do you want to overwrite the existing installation?"
+    fi
+
+    if [ $? -ne 0 ]; then
+        echo "Aborting install of lein."
+        return 0
+    fi
+
+    echo "Installing lein..."
     curl httpis://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o "$lein"
     chmod u+x "$lein"
 }
diff --git a/scripts/install_neovim b/scripts/install_neovim
--- a/scripts/install_neovim
+++ b/scripts/install_neovim
@@ -1,9 +1,30 @@
 #!/bin/bash
 
-install_neovim() {
+function yes_or_no {
+    while true; do
+        read -p "$* [y/n]: " yn
+        case $yn in
+            [Yy]*) return 0 ;;  
+            [Nn]*) return 1 ;;
+        esac
+    done
+}
+
+function install_neovim {
+    nvim="${HOME}/bin/nvim"
+
+    if [ -e ${nvim} ]; then
+        nvim -v
+        yes_or_no "nvim is already installed, do you want to overwrite the existing installation?"
+    fi
+
+    if [ $? -ne 0 ]; then
+        echo "Aborting install of neovim."
+        return 0
+    fi
+
     version=${1:-nightly}
     echo "Installing nvim ${version}..."
-    nvim="${HOME}/bin/nvim"
     nvimurl="https://github.com/neovim/neovim/releases/download/${version}/nvim-linux-x86_64.appimage"
     mkdir -p "$(dirname "$nvim")"
     curl -fL "$nvimurl" -o "$nvim" -z "$nvim"
